version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media:

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
     - "5432:5432"
  web:
    image: bdcry/foodgram:latest
    restart: always
    volumes:
      - static_volume:/code/static/
      - media:/code/media
    depends_on:
      - db
    links:
     - db:db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.0
    volumes:
      - media:/code/media
      - static_volume:/code/static/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web