# Generated by Django 2.2 on 2021-08-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210830_0151'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_unique',
        ),
    ]
