# Generated by Django 2.2 on 2021-08-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredientrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientRecipe',
        ),
    ]
