# Generated by Django 2.2 on 2021-08-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210831_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipeingredient',
        ),
    ]
